ho = ['https://timesofindia.indiatimes.com/', 'https://www.hindustantimes.com/', 'https://indianexpress.com/', 'https://www.ndtv.com/']
corona = ['https://timesofindia.indiatimes.com/coronavirus', 'https://www.hindustantimes.com/coronavirus/', 'https://www.ndtv.com/coronavirus']
eco = ['https://economictimes.indiatimes.com/', 'https://zeenews.india.com/economy']
wor = ['https://timesofindia.indiatimes.com/world', 'https://www.hindustantimes.com/world-news/', 'https://zeenews.india.com/world']
trav = ['https://timesofindia.indiatimes.com/travel', 'https://zeenews.india.com/travel']
spo = ['https://timesofindia.indiatimes.com/sports', 'https://www.hindustantimes.com/sports-news/', 'https://sports.ndtv.com/']
ci = ['https://timesofindia.indiatimes.com/city', 'https://www.hindustantimes.com/cities/']
astro = ['https://timesofindia.indiatimes.com/astrology', 'https://zeenews.india.com/horoscope']
life = ['https://timesofindia.indiatimes.com/life-style', 'https://www.hindustantimes.com/lifestyle/', 'https://food.ndtv.com/', 'https://doctor.ndtv.com/']
bus = ['https://timesofindia.indiatimes.com/business', 'https://www.hindustantimes.com/business-news/', 'https://zeenews.india.com/business']
ent = ['https://timesofindia.indiatimes.com/entertainment', 'https://www.hindustantimes.com/entertainment/', 'https://zeenews.india.com/entertainment']
edu = ['https://timesofindia.indiatimes.com/education', 'https://www.hindustantimes.com/education/', 'https://zeenews.india.com/education']
tech = ['https://www.hindustantimes.com/tech/', 'https://zeenews.india.com/technology', 'https://gadgets.ndtv.com/']

categories = [ho, corona, eco, wor, trav, spo, ci, astro, life, bus, ent, edu, tech]
Categories = ['home','coronavirus', 'ecomonics', 'world', 'travel', 'sports', 'city', 'astrology', 'lifestyle', 'business', 'entertainment', 'education', 'technology']
